// WordweeperPuzzles — word list and daily seed logic

const WORD_LIST = [
  'ABBEY','ABODE','ABUSE','ACUTE','ADORE','AGILE','AGONY','ALARM','ALERT','ALIGN',
  'ALIKE','ALIVE','ANGEL','ANGER','ANVIL','APART','APRON','ARISE','ARMOR','ARRAY',
  'ARROW','ATONE','ATTIC','AWAKE','AWARD','AWARE','AWFUL','AZURE','BADGE','BAKER',
  'BASIC','BATCH','BEARD','BEAST','BEGAN','BEGIN','BEING','BELOW','BLACK','BLADE',
  'BLANK','BLAST','BLAZE','BLEND','BLIND','BLOCK','BLOOD','BLOOM','BOARD','BONUS',
  'BRACE','BRAIN','BRAND','BRAVE','BREAD','BREAK','BRIDE','BRIEF','BRING','BROAD',
  'BROKE','BROOK','BROOM','BRUSH','BUILD','BUILT','BUNCH','BURST','CAMEL','CANDY',
  'CARGO','CARRY','CARVE','CATCH','CAUSE','CHAIN','CHAIR','CHAOS','CHARM','CHASE',
  'CHEAP','CHECK','CHEEK','CHESS','CHEST','CHIEF','CHILD','CHINA','CIVIC','CLAIM',
  'CLASH','CLASS','CLEAN','CLEAR','CLICK','CLIFF','CLING','CLOCK','CLOSE','CLOUD',
  'COAST','COMET','CORAL','COURT','COVER','CRACK','CRAFT','CRANE','CRASH','CREAK',
  'CREST','CRIME','CRISP','CROSS','CROWD','CROWN','CRUEL','CRUSH','DAISY','DANCE',
  'DECAY','DEPTH','DEVIL','DIRTY','DRAFT','DRAIN','DRAMA','DRANK','DREAD','DREAM',
  'DRINK','DROVE','DWELL','EAGER','EAGLE','EARLY','EARTH','EIGHT','ELBOW','ELITE',
  'EMBER','EMPTY','ENEMY','ENJOY','ENTER','EQUAL','ERUPT','EVENT','EXACT','EXIST',
  'EXTRA','FABLE','FAINT','FAITH','FANCY','FATAL','FEAST','FENCE','FIELD','FIGHT',
  'FINAL','FIRST','FLAME','FLARE','FLASH','FLEET','FLESH','FLOAT','FLOOD','FLOOR',
  'FLOUR','FOCUS','FORCE','FORGE','FORTH','FRAME','FRANK','FRAUD','FRESH','FRONT',
  'FROST','FRUIT','FULLY','GAUGE','GHOST','GIANT','GIVEN','GLASS','GLEAM','GLIDE',
  'GLOOM','GLOVE','GRACE','GRADE','GRAIN','GRAND','GRANT','GRASP','GRASS','GRAVE',
  'GREAT','GREEN','GREET','GRIEF','GROAN','GROSS','GROUP','GROVE','GROWN','GUARD',
  'GUESS','GUEST','GUIDE','GUILD','GUISE','GUSTO','HASTE','HAVEN','HEART','HEAVY',
  'HEDGE','HENCE','HINGE','HOIST','HONOR','HORSE','HOTEL','HOUND','HOUSE','HOVER',
  'HUMAN','HUMOR','IDEAL','IMAGE','IMPLY','INDEX','INNER','INPUT','INFER','IVORY',
  'ISSUE','JUICE','JUMPY','KARMA','KNIFE','KNOCK','KNOWN','LANCE','LAPSE','LARGE',
  'LASER','LATCH','LAUGH','LAYER','LEARN','LEASE','LEGAL','LEMON','LEVEL','LIGHT',
  'LIMIT','LINEN','LOCAL','LODGE','LOGIC','LOWER','LOYAL','LUCKY','LUNGE','MAGIC',
  'MAJOR','MANOR','MAPLE','MARCH','MARSH','MATCH','MAYOR','MEDAL','MERIT','METAL',
  'MIGHT','MIRTH','MONEY','MORAL','MOURN','MOUTH','MUSIC','NAIVE','NERVE','NIGHT',
  'NOBLE','NORTH','NOVEL','NYMPH','OCEAN','OFFER','OFTEN','OPTIC','ORDER','OUTER',
  'OZONE','PANEL','PANIC','PAPER','PARTY','PATCH','PAUSE','PEACE','PEACH','PEARL',
  'PHASE','PIANO','PILOT','PINCH','PITCH','PIXEL','PLACE','PLAIN','PLANK','PLANT',
  'PLUCK','PLUMB','PLUME','POINT','POLAR','POWER','PRESS','PRICE','PRIDE','PRIME',
  'PRINT','PRIOR','PRIZE','PROBE','PROOF','PROSE','PROUD','PROVE','PROWL','PULSE',
  'PUNCH','PUPIL','QUEEN','QUEST','QUICK','QUIET','QUOTA','QUOTE','RADAR','RAISE',
  'RANGE','RAPID','RAVEN','REACH','REALM','REBEL','REIGN','RENEW','RIVAL','RIVER',
  'RIVET','ROGUE','ROUND','ROUTE','ROYAL','RULER','RURAL','SAINT','SCALE','SCARE',
  'SCENE','SCOUT','SENSE','SERVE','SEVEN','SHADE','SHAFT','SHAKE','SHAME','SHAPE',
  'SHARE','SHARK','SHARP','SHELF','SHELL','SHIFT','SHINE','SHIRT','SHOCK','SHORE',
  'SHORT','SHOUT','SIGHT','SIXTH','SIXTY','SKILL','SKULL','SLASH','SLATE','SLAVE',
  'SLIDE','SLING','SLOTH','SMALL','SMART','SMOKE','SNAKE','SOLAR','SOLID','SOUTH',
  'SPARE','SPARK','SPEAR','SPEED','SPICE','SPIKE','SPINE','SPORT','SPRAY','STAFF',
  'STAGE','STAKE','STALE','STAMP','STAND','STARK','START','STATE','STEAL','STEAM',
  'STEEL','STEEP','STERN','STICK','STILL','STING','STOCK','STONE','STORM','STORY',
  'STOUT','STRAP','STRAW','STRIP','STUDY','STUMP','STUNT','STYLE','SUGAR','SUPER',
  'SURGE','SWAMP','SWEAR','SWEET','SWIFT','SWIRL','SWORD','TAINT','TASTE','TEACH',
  'TENSE','THEME','THICK','THIEF','THING','THINK','THIRD','THORN','THREE','TIGER',
  'TIGHT','TIMER','TITLE','TONIC','TORCH','TOTAL','TOUCH','TOUGH','TOWER','TOXIC',
  'TRACK','TRADE','TRAIL','TRAIN','TRAIT','TRASH','TREAT','TREND','TRIAL','TRICK',
  'TROOP','TROUT','TRUCE','TRULY','TRUNK','TRUST','TRUTH','TULIP','TWEAK','TWICE',
  'TWIST','ULTRA','UNDER','UNION','UNITE','UNTIL','UPPER','UPSET','URBAN','USHER',
  'UTTER','VALOR','VALUE','VALVE','VAULT','VIGOR','VIRAL','VISTA','VITAL','VIVID',
  'VOCAL','VOGUE','VOICE','VOUCH','WAGER','WATCH','WATER','WEAVE','WEDGE','WEIRD',
  'WHALE','WHEAT','WHEEL','WHILE','WHITE','WHOLE','WITCH','WOMAN','WORLD','WORRY',
  'WORTH','WRATH','WRECK','WRIST','WRITE','YACHT','YIELD','YOUNG','YOUTH','ZEBRA',
];

function getDailyPuzzle() {
  const now = new Date();
  const year  = now.getUTCFullYear();
  const month = now.getUTCMonth();      // 0-based
  const day   = now.getUTCDate();

  const epoch   = Date.UTC(2026, 0, 1);
  const today   = Date.UTC(year, month, day);
  const dayIndex = Math.max(0, Math.floor((today - epoch) / 86_400_000));

  const wordIndex = dayIndex % WORD_LIST.length;
  const word      = WORD_LIST[wordIndex];
  const seed      = year * 10000 + (month + 1) * 100 + day;

  return { word, seed, dayIndex };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WORD_LIST, getDailyPuzzle };
} else {
  window.WordweeperPuzzles = { WORD_LIST, getDailyPuzzle };
}
